# NumPy

In [1]:
import numpy as np # El bueno
#  import numpy - importa numpy pero tenemos que escribir el nombre largo
#  from numpy import * importan todas las funciones de numpy sin tener que escribir
#  el nombre de la libreria

In [2]:
l1 = [1,2,3,4,5,6,7,8]

In [4]:
x1 = np.array(l1)
x1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
x2 = np.array(l1, dtype='float32') # se puede especificar el tipo de dato del array
x2

array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)

Existen varios tipos de datos

- bool_
- int_ (entero por defecto, long en C)
- intc (entero de C)
- intp (entero para indexar,)
- int8 (-128,127), int16 (-32768,32767), int32, int64
- uint (entero sin signo, desde 0 a 255), uint16 (desde 0 a 65535), uint32, uint64

- float_ (igual a float64)
- float16 (media precisión, 1bit para el signo, 5bits para el exponente, 10bits de mantiza)
- float32 (precisión normal, 1bit para el signo, 8bits para el exopnente, 23 para la mantiza)
- float64 (1 bit para el signo, 11 para el exponente, y 52 para la mantiza)

- complex_, complex64 (64 porque los complejos tiene parte real e imaginaria que son float), complex128

In [8]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [10]:
np.arange(10) # array incremental

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(3,12, dtype=np.float) # no incluye el último en este caso

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [12]:
np.arange(4,5,0.1 # Indicar inicio, fin y el paso que incrementa

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [13]:
np.linspace(1,7, 12) # genera un array de valores que tienen la misma distancia entre sí
# se indica el inicio, final y el número de elementos del array

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [15]:
np.eye(5) # matriz identidad

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
x = np.zeros((8,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
x.reshape((4,6)) # redimensionar la matriz, pero de manera que sea la misma cantidad de elementos

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
y = np.array([[1,2,3],[4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np.ravel(y) # La función devuelve el mismo array pero unidimensional

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
y.flatten() # hace lo mismo que lo anterior, pero esto es una copia del original

array([1, 2, 3, 4, 5, 6])

In [26]:
np.transpose(y)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [27]:
# Genera el array de datos con la nueva dimensión indicada, pero que puede tener más elementos
# Lo que hace cuando se acaban los elementos, es volver a repetirlos
np.resize(y, (5,3)) 

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

### Ejercicios

1. Crear un array de datos con valores entre 5 y 120
2. Crear una matriz 4x4 con los valores desde 0 hasta 15
3. Crear la identidad 7x7
4. Crear un array de 20 elementos y transformarlos en una matrix 5x4
5. Crear un array con 20 números con los valores entre 0 y 5 espaciados de forma uniforme

In [28]:
# 1.
np.arange(5, 121)

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120])

In [34]:
# 2
x = np.arange(16)
x.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
# 3
np.eye(7, dtype='int_')

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [44]:
y = np.arange(20)
np.resize(y, (5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [45]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

# Propiedades de los arrayas

In [46]:
x = np.arange(12)
x = x.reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
x.ndim # Dimensión del array

2

In [48]:
x.shape # Dimensiones de la matriz, n x m

(3, 4)

In [49]:
x.size # Número de elementos de la matriz

12

In [50]:
x.dtype # Indica el tipo de datos que contiene el array

dtype('int64')

In [51]:
x.itemsize # Tamaño en bytes de cada elemento de la matriz

8

In [52]:
x.data # donde se almacena el buffer de los datos

In [53]:
x[2,1] # Acceder al elemento de la segunda fila, primer columna

9

In [55]:
x.shape = (4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [56]:
x[1:3, 0:2]

array([[3, 4],
       [6, 7]])

### Acceso por condición booleana

In [57]:
x = np.arange(50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [58]:
x[x > 30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [59]:
cond = x < 25
cond

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [60]:
x[cond]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [62]:
x[12:24] = 1
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

Numpy no tiene la heterogeneidad que se ve en R, es decir, no puede tener
elementos de diferentes tipos en un array

# Copias y vistas de array

In [17]:
x = np.arange(10)

In [4]:
y = x # No se copia el array x, sino que y lo referencia
y.shape = (2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
x # Por ende, si modificamos y, modificamos x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
x is y # Visto explícitamente

True

In [7]:
z = x.copy() # Usando la función copy de x, se copia el array en verdad
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
z is x # Aquí lo vemos explícitamente

False

In [9]:
# A veces distintos arrays comparten información con propiedades distintas
# Estas vistas forman parte del conjunto total que representa el array original
# A esto lo llamamos vista
t = x.view() # vista de x
t

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
t.shape = (5,2) 
t

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [12]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
s = x[0:2, 1:3] # Esto también es un vista, pues comparten información
s

array([[1, 2],
       [6, 7]])

In [15]:
s[:] = 5 # Sin embargo, al cambiar la vista, cambia el original
s

array([[5, 5],
       [5, 5]])

In [16]:
x

array([[0, 5, 5, 3, 4],
       [5, 5, 5, 8, 9]])

# Funciones universales (ufunc)
Funciones que realizan operaciones sobre cada uno de los elementos de un array sin tener que implementar un recorrido para aplicar la operación elemento a elemento.

- Funciones unarias (reciben un array): sqrt, sin, cos, **2
- Binarias (reciben dos arrays, y devuelven uno): maximum, minimum

In [23]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# Operaciones aritméticas
x+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
x - 4

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [21]:
x * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
x / 5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [24]:
# Operaciones trigonométricas
alpha = np.linspace(0,2*np.pi, 4)
alpha

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [25]:
np.sin(alpha)

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

In [26]:
np.cos(alpha)

array([ 1. , -0.5, -0.5,  1. ])

In [27]:
np.tan(alpha)

array([ 0.00000000e+00, -1.73205081e+00,  1.73205081e+00, -2.44929360e-16])

In [28]:
# Exponenciales y logaritmos
np.exp(x) # e elevado a cada uno de los elementos

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [29]:
np.exp2(x) # 2 elevado a x

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [30]:
np.power(3,x) # 3 elevado a x

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683])

In [32]:
np.power(x,2) # x elevado a 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [34]:
np.log(x) # El logaritmo de base e; además el -inf es porque el logaritmo de 0 es infinito

<ipython-input-34-de666c833898>:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [35]:
np.log2(x)

<ipython-input-35-55ee5869f62c>:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(x)


array([      -inf, 0.        , 1.        , 1.5849625 , 2.        ,
       2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ])

Existen funciones que tienen que ver con obtener datos estadísticos.

Estas pueden tener dos vertientes, como se verá a continuación

In [36]:
np.sum(x) # Esta es una función que suma todos los elementos del array

45

In [38]:
np.nansum(x) # La misma que la anterior, pero eliminar los posibles avalores NaN

45

In [4]:
np.prod(x)

0

In [5]:
np.mean(x)

4.5

In [24]:
np.median(x)

4.5

In [7]:
np.min(x)

0

In [8]:
np.max(x)

9

In [10]:
np.std(x) # desviación típica

2.8722813232690143

In [11]:
np.var(x) # varianza

8.25

In [12]:
np.argmin(x) # el índice del valor más pequeño

0

In [13]:
np.argmax(x) # el índice del valor máximo

9

In [14]:
np.percentile(x, q=0.1) # calcula los percentiles, dando el cuartil a evaluar

0.009000000000000001

In [18]:
y = np.array([True, True, False, True])

In [19]:
np.any(y) # devuelve true si uno de los elementos es True

True

In [20]:
np.all(y) # devuelve true si todos los elementos son True

False

En caso de tener arrays multidimensionales, se le puede agregar el parámetro axis a las funciones anteriores para indicar donde usar la función

In [39]:
np.random.seed(2020) # Permite dar una semilla aleatoria
# CUando se fija, todas las ejecuciones obtendrán la misma secuencia de números aleatorios
# Esto por que los números no son totalmente aleatorios, si no pseudoaleatorios
# Se planta antes la semilla
z = np.random.random((3,5))
z

array([[0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873],
       [0.21695427, 0.27647714, 0.34331559, 0.86215894, 0.15669967],
       [0.14088724, 0.75708028, 0.73632492, 0.35566309, 0.34109302]])

In [40]:
z.sum()

7.164822899895267

In [41]:
z.sum(axis=0) # Suma por columnas, donde devuelve las 5 sumas de cada columna

array([1.34411834, 1.90694937, 1.58938604, 1.48965774, 0.83471141])

In [42]:
z.sum(axis=1) # suma por filas

array([2.97816874, 1.85560561, 2.33104855])